// app/disclaimer.js  →  place in:  app/disclaimer.js
import React from "react";
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Linking,
} from "react-native";
import { LinearGradient } from "expo-linear-gradient";
import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { COLORS, SPACING, RADIUS } from "../src/constants/theme";

const DISCLAIMER_SECTIONS = [
  {
    icon: "chatbubbles",
    color: "#a855f7",
    bg: "rgba(168,85,247,0.12)",
    border: "rgba(168,85,247,0.22)",
    title: "User-Generated Content",
    content:
      "Zonnecto is a platform for user-to-user communication. All messages, media and content shared on Zonnecto are generated by users, not by Zonnecto. We do not endorse, verify, or take responsibility for any content shared between users. Users are solely responsible for the content they share.",
  },
  {
    icon: "shield-half",
    color: "#22d3ee",
    bg: "rgba(34,211,238,0.1)",
    border: "rgba(34,211,238,0.18)",
    title: "No Guarantee of Safety",
    content:
      "While we take significant measures to ensure user safety — including content moderation, reporting tools and blocking features — Zonnecto cannot guarantee that all interactions on the platform will be safe or appropriate. Users should exercise caution and use their own judgement when communicating with strangers online.",
  },
  {
    icon: "warning",
    color: "#fb923c",
    bg: "rgba(251,146,60,0.1)",
    border: "rgba(251,146,60,0.18)",
    title: "No Liability for Third-Party Actions",
    content:
      "Zonnecto is not liable for any actions, behaviour, or content of its users. Any harm, emotional distress, or damage arising from interactions between users is solely the responsibility of those involved. We strongly encourage users to report any abusive or harmful behaviour using the in-app tools.",
  },
  {
    icon: "link",
    color: "#4ade80",
    bg: "rgba(74,222,128,0.1)",
    border: "rgba(74,222,128,0.18)",
    title: "External Links Prohibited",
    content:
      "Sharing links to external websites or resources is strictly prohibited on Zonnecto. Any links shared in chats are blocked and not accessible. Zonnecto is not responsible for any external websites or content that users attempt to share.",
  },
  {
    icon: "medical",
    color: "#38bdf8",
    bg: "rgba(56,189,248,0.1)",
    border: "rgba(56,189,248,0.18)",
    title: "Not Professional Advice",
    content:
      "Nothing on Zonnecto should be construed as professional, legal, medical, financial, or psychological advice. Any information shared by users is personal opinion and should not be relied upon as a substitute for professional advice. Please consult qualified professionals for such matters.",
  },
  {
    icon: "refresh-circle",
    color: "#818cf8",
    bg: "rgba(129,140,248,0.1)",
    border: "rgba(129,140,248,0.18)",
    title: "Service Availability",
    content:
      "Zonnecto does not guarantee uninterrupted, error-free service. We reserve the right to modify, suspend, or discontinue any part of the service at any time without notice. We are not liable for any loss or inconvenience caused by service interruptions or changes.",
  },
  {
    icon: "person-remove",
    color: "#ef4444",
    bg: "rgba(239,68,68,0.1)",
    border: "rgba(239,68,68,0.18)",
    title: "Age Restriction",
    content:
      "Zonnecto is strictly for users aged 18 and above. By using this platform, you confirm that you are 18 or older. If you are underage, please stop using this service immediately. We are not responsible for underage access that occurs in violation of our Terms of Service.",
  },
  {
    icon: "globe",
    color: "#f59e0b",
    bg: "rgba(245,158,11,0.1)",
    border: "rgba(245,158,11,0.18)",
    title: "Jurisdiction",
    content:
      "This disclaimer and all legal matters related to Zonnecto shall be governed by and construed in accordance with the laws of India. Any disputes arising from the use of Zonnecto shall be subject to the exclusive jurisdiction of the courts in India.",
  },
];

export default function DisclaimerScreen() {
  const router = useRouter();
  const insets = useSafeAreaInsets();

  return (
    <View style={s.container}>
      <View style={s.orb1} />
      <View style={s.orb2} />

      <View style={[s.header, { paddingTop: insets.top + 8 }]}>
        <TouchableOpacity onPress={() => router.back()} style={s.backBtn}>
          <Ionicons name="arrow-back" size={20} color="#fff" />
        </TouchableOpacity>
        <Text style={s.headerTitle}>Disclaimer</Text>
        <View style={{ width: 36 }} />
      </View>

      <ScrollView
        contentContainerStyle={[
          s.scroll,
          { paddingBottom: insets.bottom + 40 },
        ]}
        showsVerticalScrollIndicator={false}
      >
        {/* Hero */}
        <View style={s.heroBanner}>
          <LinearGradient
            colors={["transparent", "rgba(251,146,60,0.55)", "transparent"]}
            start={{ x: 0, y: 0 }}
            end={{ x: 1, y: 0 }}
            style={s.topLine}
          />
          <View style={s.heroIconCircle}>
            <Ionicons name="alert-circle" size={32} color="#fb923c" />
          </View>
          <Text style={s.heroTitle}>Disclaimer</Text>
          <Text style={s.heroSub}>
            Please read this disclaimer carefully. By using Zonnecto, you
            acknowledge and agree to the following terms.
          </Text>
          <View style={s.updatedRow}>
            <Ionicons name="time-outline" size={13} color={COLORS.textMuted} />
            <Text style={s.updatedText}>Last updated: January 2025</Text>
          </View>
        </View>

        {/* Important notice */}
        <View style={s.importantBox}>
          <View style={s.importantHead}>
            <Ionicons name="warning" size={16} color="#fb923c" />
            <Text style={s.importantTitle}>Important Notice</Text>
          </View>
          <Text style={s.importantText}>
            Zonnecto facilitates anonymous connections between strangers. While
            we work hard to maintain a safe community, please use common sense
            and protect your personal information at all times.
          </Text>
        </View>

        {/* Sections */}
        {DISCLAIMER_SECTIONS.map((sec, i) => (
          <View key={i} style={[s.secCard, { borderColor: sec.border }]}>
            <View style={s.secHead}>
              <View
                style={[
                  s.secIcon,
                  { backgroundColor: sec.bg, borderColor: sec.border },
                ]}
              >
                <Ionicons name={sec.icon} size={17} color={sec.color} />
              </View>
              <Text style={s.secTitle}>{sec.title}</Text>
            </View>
            <Text style={s.secText}>{sec.content}</Text>
          </View>
        ))}

        {/* Safety tips */}
        <View style={s.safetyBox}>
          <LinearGradient
            colors={["rgba(74,222,128,0.08)", "rgba(6,182,212,0.04)"]}
            style={s.safetyGrad}
          >
            <View style={s.safetyHead}>
              <Ionicons
                name="shield-checkmark"
                size={18}
                color={COLORS.green}
              />
              <Text style={s.safetyTitle}>Stay Safe Online</Text>
            </View>
            {[
              "Never share your real name, phone number or home address",
              "Don't send money or financial information to strangers",
              "Report suspicious behaviour using the in-app report button",
              "Block users who make you feel uncomfortable",
              "Trust your instincts — if something feels wrong, exit the chat",
            ].map((tip, i) => (
              <View key={i} style={s.tipRow}>
                <Ionicons
                  name="checkmark-circle"
                  size={14}
                  color={COLORS.green}
                />
                <Text style={s.tipText}>{tip}</Text>
              </View>
            ))}
          </LinearGradient>
        </View>

        {/* Contact */}
        <View style={s.contactBox}>
          <Text style={s.contactTitle}>Questions or Concerns?</Text>
          <Text style={s.contactText}>
            If you have any questions about this disclaimer or need to report a
            serious issue, contact us at{" "}
            <Text
              style={s.contactLink}
              onPress={() => Linking.openURL("mailto:zonnecto@gmail.com")}
            >
              zonnecto@gmail.com
            </Text>
          </Text>
          <TouchableOpacity
            onPress={() => router.push("/contact")}
            style={s.contactBtn}
            activeOpacity={0.85}
          >
            <LinearGradient
              colors={["#7c3aed", "#6366f1", "#0891b2"]}
              start={{ x: 0, y: 0 }}
              end={{ x: 1, y: 0 }}
              style={s.contactBtnGrad}
            >
              <Ionicons name="mail" size={15} color="#fff" />
              <Text style={s.contactBtnText}>Contact Support</Text>
            </LinearGradient>
          </TouchableOpacity>
        </View>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bg },
  orb1: {
    position: "absolute",
    width: 300,
    height: 300,
    borderRadius: 150,
    backgroundColor: "rgba(251,146,60,0.07)",
    top: -80,
    right: -70,
  },
  orb2: {
    position: "absolute",
    width: 250,
    height: 250,
    borderRadius: 125,
    backgroundColor: "rgba(124,58,237,0.08)",
    bottom: 100,
    left: -60,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: SPACING.lg,
    paddingBottom: SPACING.md,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.06)",
    backgroundColor: "rgba(7,7,16,0.95)",
  },
  backBtn: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: { fontSize: 16, fontWeight: "700", color: "#fff" },
  scroll: { paddingHorizontal: SPACING.lg, paddingTop: SPACING.lg },
  heroBanner: {
    backgroundColor: COLORS.bgCard,
    borderRadius: RADIUS.xl,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: SPACING.xl,
    alignItems: "center",
    marginBottom: SPACING.lg,
    overflow: "hidden",
    position: "relative",
  },
  topLine: { position: "absolute", top: 0, left: "5%", right: "5%", height: 1 },
  heroIconCircle: {
    width: 76,
    height: 76,
    borderRadius: 22,
    backgroundColor: "rgba(251,146,60,0.12)",
    borderWidth: 1,
    borderColor: "rgba(251,146,60,0.25)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: SPACING.md,
  },
  heroTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: "#fff",
    marginBottom: SPACING.sm,
  },
  heroSub: {
    fontSize: 13,
    color: COLORS.textMuted,
    textAlign: "center",
    lineHeight: 20,
    marginBottom: SPACING.md,
  },
  updatedRow: { flexDirection: "row", alignItems: "center", gap: 5 },
  updatedText: { fontSize: 12, color: COLORS.textMuted },
  importantBox: {
    backgroundColor: "rgba(251,146,60,0.08)",
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: "rgba(251,146,60,0.22)",
    padding: SPACING.md,
    marginBottom: SPACING.lg,
  },
  importantHead: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    marginBottom: SPACING.sm,
  },
  importantTitle: { fontSize: 14, fontWeight: "700", color: "#fb923c" },
  importantText: { fontSize: 13, color: COLORS.textMuted, lineHeight: 20 },
  secCard: {
    backgroundColor: COLORS.bgCard,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    padding: SPACING.lg,
    marginBottom: SPACING.sm,
  },
  secHead: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    marginBottom: SPACING.sm,
  },
  secIcon: {
    width: 38,
    height: 38,
    borderRadius: 11,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  secTitle: { flex: 1, fontSize: 14, fontWeight: "700", color: "#fff" },
  secText: { fontSize: 13, color: COLORS.textMuted, lineHeight: 21 },
  safetyBox: {
    borderRadius: RADIUS.xl,
    overflow: "hidden",
    marginBottom: SPACING.lg,
    borderWidth: 1,
    borderColor: "rgba(74,222,128,0.2)",
  },
  safetyGrad: { padding: SPACING.lg },
  safetyHead: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    marginBottom: SPACING.md,
  },
  safetyTitle: { fontSize: 15, fontWeight: "700", color: COLORS.green },
  tipRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: SPACING.sm,
    marginBottom: 7,
  },
  tipText: { flex: 1, fontSize: 13, color: COLORS.textMuted, lineHeight: 19 },
  contactBox: {
    backgroundColor: COLORS.bgCard,
    borderRadius: RADIUS.xl,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: SPACING.xl,
    alignItems: "center",
  },
  contactTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#fff",
    marginBottom: SPACING.sm,
  },
  contactText: {
    fontSize: 13,
    color: COLORS.textMuted,
    textAlign: "center",
    lineHeight: 20,
    marginBottom: SPACING.lg,
  },
  contactLink: { color: COLORS.purplePale, fontWeight: "600" },
  contactBtn: { borderRadius: RADIUS.md, overflow: "hidden", width: "100%" },
  contactBtnGrad: {
    flexDirection: "row",
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  contactBtnText: { color: "#fff", fontSize: 14, fontWeight: "700" },
});
