import React, { useState } from "react";
import { ZnNavbar, ZnFooter } from "../components/ZnLayout";

const sections = [
  {
    icon: (
      <svg
        width="18"
        height="18"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
        strokeWidth="1.8"
      >
        <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
      </svg>
    ),
    title: "General Use Disclaimer",
    content: `Zonnecto is a platform designed for anonymous communication. By using Zonnecto, you acknowledge that you do so at your own risk. The platform is provided "as is" without any guarantees of uptime, reliability, or fitness for a particular purpose.

We make no warranties, expressed or implied, regarding the accuracy, completeness, or suitability of any content exchanged on this platform.`,
  },
  {
    icon: (
      <svg
        width="18"
        height="18"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
        strokeWidth="1.8"
      >
        <path d="M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2" />
        <circle cx="9" cy="7" r="4" />
        <path d="M23 21v-2a4 4 0 00-3-3.87M16 3.13a4 4 0 010 7.75" />
      </svg>
    ),
    title: "User-Generated Content",
    content: `All messages, content, and communications on Zonnecto are generated by users. Zonnecto does not pre-screen, review, or endorse any user-generated content.

We are not responsible for any content that is offensive, harmful, inaccurate, or otherwise objectionable. Users are solely responsible for the content they share. Zonnecto reserves the right to remove content and ban users who violate our community standards.`,
  },
  {
    icon: (
      <svg
        width="18"
        height="18"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
        strokeWidth="1.8"
      >
        <circle cx="12" cy="12" r="10" />
        <line x1="12" y1="8" x2="12" y2="12" />
        <line x1="12" y1="16" x2="12.01" y2="16" />
      </svg>
    ),
    title: "Age Restriction",
    content: `Zonnecto is strictly for users aged 18 and above. By registering and using this platform, you confirm that you are at least 18 years old.

If we discover that a user is under 18, we will immediately terminate their account without notice. Parents or guardians who believe their minor has accessed Zonnecto should contact us immediately at zonnecto@gmail.com.`,
  },
  {
    icon: (
      <svg
        width="18"
        height="18"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
        strokeWidth="1.8"
      >
        <path d="M10.29 3.86L1.82 18a2 2 0 001.71 3h16.94a2 2 0 001.71-3L13.71 3.86a2 2 0 00-3.42 0z" />
        <line x1="12" y1="9" x2="12" y2="13" />
        <line x1="12" y1="17" x2="12.01" y2="17" />
      </svg>
    ),
    title: "No Liability for User Interactions",
    content: `Zonnecto serves as a platform to facilitate communication and bears no responsibility for:

• Emotional distress caused by interactions with other users
• Any financial loss resulting from sharing personal information
• Physical harm resulting from arranging in-person meetings with other users
• Any form of harassment, abuse, or misconduct by other users

We strongly advise users never to share personal identifying information, financial details, or agree to meet strangers in person through connections made on this platform.`,
  },
  {
    icon: (
      <svg
        width="18"
        height="18"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
        strokeWidth="1.8"
      >
        <rect x="3" y="11" width="18" height="11" rx="2" ry="2" />
        <path d="M7 11V7a5 5 0 0110 0v4" />
      </svg>
    ),
    title: "Privacy & Data",
    content: `While Zonnecto is designed with privacy in mind, we cannot guarantee complete anonymity. User IP addresses and session data may be logged for security and moderation purposes.

We do not sell user data to third parties. However, in the event of a lawful request from authorities regarding illegal activity, we may be required to disclose certain information as permitted by applicable law.`,
  },
  {
    icon: (
      <svg
        width="18"
        height="18"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
        strokeWidth="1.8"
      >
        <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z" />
        <polyline points="14 2 14 8 20 8" />
      </svg>
    ),
    title: "Changes to This Disclaimer",
    content: `Zonnecto reserves the right to modify this disclaimer at any time without prior notice. Continued use of the platform following any changes constitutes your acceptance of the updated terms.

This disclaimer was last updated in 2026. For questions about this disclaimer, contact us at zonnecto@gmail.com.`,
  },
];

export default function Disclaimer() {
  const [activeIdx, setActiveIdx] = useState(null);

  return (
    <>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Syne:wght@400;600;700;800&family=DM+Sans:wght@300;400;500&display=swap');
        * { box-sizing: border-box; margin: 0; padding: 0; }
        .zn-bg { min-height: 100vh; background: #070710; font-family: 'DM Sans', sans-serif; position: relative; display: flex; flex-direction: column; overflow-x: hidden; }
        .zn-orb { position: fixed; border-radius: 50%; filter: blur(100px); opacity: 0.11; pointer-events: none; }
        .zn-orb-1 { width: 500px; height: 500px; background: radial-gradient(circle,#a855f7,#7c3aed); top: -150px; left: -100px; }
        .zn-orb-2 { width: 400px; height: 400px; background: radial-gradient(circle,#f87171,#dc2626); bottom: -100px; right: -100px; opacity: 0.07; }
        .zn-grid { position: fixed; inset: 0; pointer-events: none; background-image: linear-gradient(rgba(139,92,246,0.04) 1px,transparent 1px),linear-gradient(90deg,rgba(139,92,246,0.04) 1px,transparent 1px); background-size: 48px 48px; }

        .zn-content { max-width: 820px; margin: 0 auto; padding: 3.5rem 2rem 4rem; flex: 1; position: relative; z-index: 1; }

        .disc-hero { margin-bottom: 2.5rem; animation: fadeUp 0.5s cubic-bezier(0.16,1,0.3,1) both; }
        @keyframes fadeUp { from{opacity:0;transform:translateY(18px)} to{opacity:1;transform:translateY(0)} }
        .disc-tag {
          display: inline-flex; align-items: center; gap: 0.4rem;
          background: rgba(248,113,113,0.08); border: 1px solid rgba(248,113,113,0.2);
          color: #f87171; padding: 0.3rem 0.85rem; border-radius: 20px;
          font-size: 0.72rem; letter-spacing: 0.1em; text-transform: uppercase; font-weight: 600;
          margin-bottom: 1rem;
        }
        .disc-hero h1 {
          font-family: 'Syne', sans-serif; font-size: clamp(1.8rem,4vw,2.8rem); font-weight: 800;
          color: #fff; letter-spacing: -0.03em; line-height: 1.1; margin-bottom: 0.9rem;
        }
        .disc-hero h1 span { background: linear-gradient(135deg,#f87171,#c084fc); -webkit-background-clip:text; -webkit-text-fill-color:transparent; background-clip:text; }
        .disc-hero p { color: rgba(255,255,255,0.38); font-size: 0.9rem; line-height: 1.6; }

        /* WARNING BOX */
        .disc-warning {
          display: flex; align-items: flex-start; gap: 0.85rem;
          background: rgba(248,113,113,0.06); border: 1px solid rgba(248,113,113,0.18);
          border-radius: 14px; padding: 1.1rem 1.25rem; margin-bottom: 2rem;
          animation: fadeUp 0.4s 0.1s cubic-bezier(0.16,1,0.3,1) both;
        }
        .disc-warning-icon { color: #f87171; flex-shrink: 0; margin-top: 1px; }
        .disc-warning p { font-size: 0.82rem; color: rgba(255,255,255,0.5); line-height: 1.55; }
        .disc-warning strong { color: #fca5a5; }

        /* SECTIONS */
        .disc-sections { display: flex; flex-direction: column; gap: 0.6rem; }
        .disc-section {
          background: rgba(255,255,255,0.03); border: 1px solid rgba(255,255,255,0.07);
          border-radius: 14px; overflow: hidden; transition: border-color 0.2s;
          animation: fadeUp 0.4s cubic-bezier(0.16,1,0.3,1) both;
        }
        .disc-section:hover { border-color: rgba(139,92,246,0.18); }
        .disc-section-open { border-color: rgba(139,92,246,0.22) !important; }
        .disc-section-header {
          display: flex; align-items: center; justify-content: space-between;
          padding: 1.1rem 1.3rem; cursor: pointer; gap: 1rem;
          user-select: none;
        }
        .disc-section-left { display: flex; align-items: center; gap: 0.75rem; }
        .disc-section-icon {
          width: 34px; height: 34px; border-radius: 9px; flex-shrink: 0;
          background: rgba(139,92,246,0.1); border: 1px solid rgba(139,92,246,0.18);
          display: flex; align-items: center; justify-content: center; color: #c084fc;
        }
        .disc-section-title { font-family: 'Syne', sans-serif; font-size: 0.88rem; font-weight: 700; color: #fff; }
        .disc-chevron { color: rgba(255,255,255,0.3); transition: transform 0.25s; flex-shrink: 0; }
        .disc-chevron-open { transform: rotate(180deg); color: #c084fc; }
        .disc-section-body {
          max-height: 0; overflow: hidden; transition: max-height 0.35s ease, padding 0.25s;
          border-top: 0px solid rgba(255,255,255,0.06);
        }
        .disc-section-body-open {
          max-height: 600px; padding-bottom: 1.3rem;
          border-top: 1px solid rgba(255,255,255,0.06);
        }
        .disc-section-content {
          padding: 1.1rem 1.3rem 0;
          font-size: 0.83rem; color: rgba(255,255,255,0.42); line-height: 1.72;
          white-space: pre-line;
        }

        /* FOOTER NOTE */
        .disc-footer-note {
          margin-top: 2rem; text-align: center;
          background: rgba(255,255,255,0.02); border: 1px solid rgba(255,255,255,0.06);
          border-radius: 12px; padding: 1.25rem;
          font-size: 0.78rem; color: rgba(255,255,255,0.25); line-height: 1.6;
          animation: fadeUp 0.4s 0.3s cubic-bezier(0.16,1,0.3,1) both;
        }
        .disc-footer-note a { color: #c084fc; text-decoration: none; }
        .disc-footer-note a:hover { text-decoration: underline; }

        @media(max-width:768px){
          .zn-content { padding: 2.5rem 1.25rem 3rem; }
          .disc-hero h1 { font-size: clamp(1.6rem,5vw,2.2rem); }
          .disc-section-title { font-size: 0.84rem; }
          .disc-warning { padding: 1rem 1.1rem; }
        }
        @media(max-width:560px){
          .zn-content { padding: 2rem 1rem 2.5rem; }
          .disc-section-header { padding: 0.9rem 1rem; }
          .disc-section-content { padding: 0.9rem 1rem 0; font-size: 0.8rem; }
          .disc-section-icon { width: 30px; height: 30px; border-radius: 8px; }
          .disc-warning { gap: 0.65rem; }
          .disc-warning p { font-size: 0.79rem; }
        }
        @media(max-width:400px){
          .zn-content { padding: 1.5rem 0.85rem 2rem; }
          .disc-hero h1 { font-size: 1.5rem; }
          .disc-hero p { font-size: 0.84rem; }
          .disc-section-title { font-size: 0.8rem; }
          .disc-footer-note { font-size: 0.74rem; padding: 1rem; }
        }
      `}</style>

      <div className="zn-bg">
        <div className="zn-orb zn-orb-1" />
        <div className="zn-orb zn-orb-2" />
        <div className="zn-grid" />

        <ZnNavbar />

        <div className="zn-content">
          <div className="disc-hero">
            <div className="disc-tag">
              <svg width="9" height="9" fill="currentColor" viewBox="0 0 8 8">
                <circle cx="4" cy="4" r="4" />
              </svg>
              Legal
            </div>
            <h1>
              Platform <span>Disclaimer</span>
            </h1>
            <p>
              Please read this disclaimer carefully before using Zonnecto. By
              accessing or using our platform, you acknowledge and agree to the
              terms outlined below.
            </p>
          </div>

          <div className="disc-warning">
            <div className="disc-warning-icon">
              <svg
                width="18"
                height="18"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                strokeWidth="2"
              >
                <path d="M10.29 3.86L1.82 18a2 2 0 001.71 3h16.94a2 2 0 001.71-3L13.71 3.86a2 2 0 00-3.42 0z" />
                <line x1="12" y1="9" x2="12" y2="13" />
                <line x1="12" y1="17" x2="12.01" y2="17" />
              </svg>
            </div>
            <p>
              <strong>Important:</strong> Zonnecto is strictly for users aged 18
              and above. By using this platform, you confirm you are an adult
              and accept full responsibility for your interactions. Never share
              personal identifying information with strangers online.
            </p>
          </div>

          <div className="disc-sections">
            {sections.map((s, i) => {
              const open = activeIdx === i;
              return (
                <div
                  key={i}
                  className={`disc-section ${open ? "disc-section-open" : ""}`}
                  style={{ animationDelay: `${i * 0.05}s` }}
                >
                  <div
                    className="disc-section-header"
                    onClick={() => setActiveIdx(open ? null : i)}
                  >
                    <div className="disc-section-left">
                      <div className="disc-section-icon">{s.icon}</div>
                      <div className="disc-section-title">{s.title}</div>
                    </div>
                    <svg
                      className={`disc-chevron ${open ? "disc-chevron-open" : ""}`}
                      width="16"
                      height="16"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                      strokeWidth="2"
                    >
                      <path d="M6 9l6 6 6-6" />
                    </svg>
                  </div>
                  <div
                    className={`disc-section-body ${open ? "disc-section-body-open" : ""}`}
                  >
                    <div className="disc-section-content">{s.content}</div>
                  </div>
                </div>
              );
            })}
          </div>

          <div className="disc-footer-note">
            This disclaimer was last updated in 2026. For legal inquiries,
            contact us at <a href="mailto:zonnecto@gmail.com">zonnecto.com</a>.
            By continuing to use Zonnecto, you agree to be bound by this
            disclaimer and our <a href="/terms">Terms & Conditions</a> and{" "}
            <a href="/privacy">Privacy Policy</a>.
          </div>
        </div>

        <ZnFooter />
      </div>
    </>
  );
}
